### ISSUE TITLE
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/3966974312_circleci_config.yml.

### ISSUE THREAD

**Issue by miguelmota** [CircleCI-Public/circleci-cli#1036]
## Meta:

`circleci local execute` fails with docker volume bind error. Seems like it can't map the generated temp file correctly.

**CircleCI CLI Version:**
```sh
$ circleci version
0.1.29936+c2d98ee (release)
```

**Operating System:**
```sh
$ uname -a
Linux archlinux 6.6.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 04 Dec 2023 00:29:19 +0000 x86_64 GNU/Linux
```

**CircleCI CLI Diagnostic:**
```
$ circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/linux/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
```

---

## Current behavior:

`/tmp/hello.yml`

```yml
version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

workflows:
  my-workflow:
    jobs:
      - hello-job
```

```sh
$ circleci local execute hello-job --config /tmp/hello.yml
Fetching latest build environment...
Docker image digest: sha256:798518d02e27bacdc567990980517f81884097eab33635b1450571bc1a7feed9
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/3966974312_circleci_config.yml.
See 'docker run --help'.
```

## Expected behavior:
Run image
