### ISSUE TITLE
Validation fails for github/gitlab trigger_parameters

### ISSUE THREAD

**Issue by unickq** [CircleCI-Public/circleci-cli#1060]
## Meta:

**CircleCI CLI Version:**
0.1.30549+735ecd3

**Operating System:**
macos

I'm trying to use https://circleci.com/docs/pipeline-variables/#pipeline-values

```yml
  - run:
      name: Run tests
      command: |
        export MESSAGE = "<< pipeline.trigger_parameters.github_app.commit_message >>"
```

But on `circleci config validate` have this.

```
Error: config compilation contains errors: config compilation contains errors:
        - Error calling job: 'test-ui'
        - Unknown variable(s): commit_message
```

Any github, gitlab params fail
