### ISSUE TITLE
Workflow still triggered even when the PR is closed

### ISSUE THREAD

**Issue by barth12** [CircleCI-Public/circleci-cli#1096]
## Meta:

**CircleCI CLI Version:**
0.1.30995+77b1f51 

**Operating System:**
MacOS

---

## Current behavior:
I've identified what appears to be a bug in CircleCI's workflow trigger functionality.
My workflow is configured to trigger only under specific conditions:
	- when a pull request is labeled
	- when a pull request is synchronized
The workflow is incorrectly triggering when a pull request is closed and I subsequently push changes to the feature branch that was the basis for that PR.

Here's my config:

```
workflows:
  run_on_pr:
    when:
      or:
        - << pipeline.event.name >> == "pull_request" and << pipeline.event.action >> == "labeled"
        - << pipeline.event.name >> == "pull_request" and << pipeline.event.action >> == "synchronize"
```

Here are the triggers I am using:
<img width="374" alt="Image" src="https://github.com/user-attachments/assets/2b27e030-cdef-4874-83b7-21c41a7ef8e0" />

This workflow correctly triggers when a pull request is labeled or synchronized. However, it's also unexpectedly triggering after a pull request is closed and there is a push to the feature branch which was the basis for this PR.

## Expected behavior:
Shouldn't be triggered after the pull request is closed.
