### ISSUE TITLE
circleci config validate does not check that jobs listed in a workflow are defined

### ISSUE THREAD

**Issue by marcomorain** [CircleCI-Public/circleci-cli#11]
When a job is listed in a workflow but missing from the jobs section, the config validator will report the config as valid but will fail immediately when pushed to CircleCI:

```
* Cannot find a job named `build` to run in the `jobs:` section of your configuration file.
```

The validator should ensure that all jobs listed in workflows are actually defined.

https://github.com/circleci/local-cli/issues/20#issuecomment-401071508

cc @federicobond

**Comment by marcomorain** [comment]
```
version: 2.1
jobs:
  foo:
    machine: true
    steps: 
      - checkout

workflows:
  workflow:
    jobs:
      - foo
      - bar

```

```
$ circleci config validate
Error: Error calling workflow: 'workflow': Cannot find a definition for job named bar
```
