### ISSUE TITLE
circleci config validate assumes 2.1 config version

### ISSUE THREAD

**Issue by sr-ix** [CircleCI-Public/circleci-cli#146]
This is very similar to the bug on the UI where any newly configured job automatically opts one into an experimental 2.1 config feature set. This is not desired or expected.

CircleCI's cli version is `0.1.1430+9788d75`

One can use these dummy config to reproduce by running `circleci config validate`

```yaml
# generic v2.x config with filter
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo "this is just a test"
```
_Unexpected_ output:
`Error: Job "build" has filters configured in the job definition. These filters are incompatible with workflows.`

```yaml
# generic v2.x config with filter
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    # branches:
    #   only:
    #     - master
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo "this is just a test"
```
_Expected_ output:
`Error: Job "build" has filters configured in the job definition. These filters are incompatible with workflows.`

```yaml
# explicitly use v2.0 config with filter
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo "this is just a test"
```
_Expected_ output:
`Error: Job "build" has filters configured in the job definition. These filters are incompatible with workflows.`

```yaml
# explicitly use v2.1 config with filter
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo "this is just a test"
```
_Expected_ output:
`Error: jobs: build: extraneous key [branches] is not permitted`
