### ISSUE TITLE
Validate accepts missing 'parameters.' prefix when referencing parameters

### ISSUE THREAD

**Issue by toreandreb** [CircleCI-Public/circleci-cli#161]
I am using version 0.1.3257+b197d90 of the CLI.

I have a parameter called 'myparam'. When I use this parameter, and ran validation, the following happened:

1. echo << myparam >>   # Validated ok
2. echo << notmyparam >>  # Validated with error
3. echo << parameters.myparam >>  # Validated ok 
4. echo << parameters.notmyparam >>  # Validated with error

The only alternative that actually works is number 3. Number 1 will not work. When I ran 'circleci config process', it was not able to find the parameter. 

Should number 1 result in a validation error, or should 'circleci config process' be able to find the parameter? 

Btw, when I check in number 1, the circleci.com processing result in the same as the CLI processing.

**Comment by marcomorain** [comment]
👍 good idea!

**Comment by marcomorain** [comment]
Logged internally as [CIRCLE-25064](https://circleci.atlassian.net/browse/CIRCLE-25064)

**Comment by johnswanson** [comment]
@toreandreb thank you for creating this issue! I believe that this has been fixed now -- any chance you (or anyone else running into this) can confirm?

For testing, I'm using the following config, let me know if this isn't representative:
```
version: 2.1
jobs:
  build:
    parameters:
      myparam:
        type: string
        default: "foo"
    machine: true
    steps:
      - run: echo << myparam >>
workflows:
  workflow:
    jobs:
      - build:
          myparam: bar
```

When I attempt to run that through `circleci config validate` or `circleci config process` I get:

```
Error: Error calling workflow: 'workflow'
Error calling job: 'build'
Unknown variable(s): myparam
```

Thanks again for raising this!
