### ISSUE TITLE
Something breaks lines unexpectedly

### ISSUE THREAD

**Issue by matfax** [CircleCI-Public/circleci-cli#209]
Today, I noticed that recently, unexpected line breaks occur with long commands.

This is a shortened example from the `circleci orb source` of a dev orb I'm working on:
```yaml
steps:
  - run:
        command: |
          circleci orb publish << parameters.orb-path >> << parameters.orb-ref >> <<# parameters.publish-token-variable >>--token << parameters.publish-token-variable >> <</ parameters.publish-token-variable >>
```

Here the config-expanded version from the online console:
```bash
circleci orb publish ./.orbspace/orb.yml ${ORB_PUBLISHING_NAMESPACE}/${ORB_PUBLISHING_NAME}@dev:${CIRCLE_BUILD_NUM}
 --token ${ORB_PUBLISHING_TOKEN} 
```

Notice the unexpected new line break before `--token`.

The confusing thing about this issue is that the same orb source code works from a previous orb version. That only makes sense to me if you choose the cli version depending on the orb version, otherwise I'm confused why the same config, same orb source and same command should be parsed differently just because the version is newer.
