### ISSUE TITLE
cli config pack not working

### ISSUE THREAD

**Issue by jasonkuhrt** [CircleCI-Public/circleci-cli#276]
Upon request ported from https://discuss.circleci.com/t/circleci-config-pack-not-working/28568
```
❯ cci version
0.1.5389+4379bab
```
```
❯ tree src/test
src/test
├── @orb.yml
├── commands.yml
├── executors.yml
└── jobs.yml

0 directories, 4 files
```
```yml
❯ cat src/test/@orb.yml
# TODO foobar

version: 2.1
description: todo

orbs:
  slack: circleci/slack@0.1.10
  aws-cli: circleci/aws-cli@0.1.6
  utils: dialogue/sandbox@dev:utils
```
```yml
❯ cat src/test/commands.yml
aliases:
  - &param_foo
    foo:
      type: string

foo_command:
  parameters:
    <<: *param_foo
  steps:
    - run: echo '<<parameters.foo>>'
```
```yml
❯ cat src/test/executors.yml
python:
  parameters:
    node:
      type: enum
      enum:
        - node
        - node-browsers
        - node-browsers-legacy
      default: node
    version:
      type: enum
      enum:
        - "3.7"
        - "3.7.2"
        - "3.7.1"
        - "3.7.0"
        - "3.6"
        - "3.6.8"
        - "3.6.7"
        - "3.6.6"
        - "3.6.5"
        - "3.6.4"
        - "3.6.3"
      default: "3.7"
  docker:
    - image: circleci/python:<<parameters.version>>-<<parameters.node>>
```
```yml
❯ cat src/test/jobs.yml
aliases:
  - &param_bar
    bar:
      type: string

bar_job:
  parameters:
    <<: *param_bar
  steps:
    - run:
        name: bar job
        commandn: echo '<<parameters.bar>>'
```

Result
```yml
❯ cci config pack src/test
aliases:
- bar:
    type: string
bar_job:
  parameters:
    bar:
      type: string
  steps:
  - run:
      commandn: echo '<<parameters.bar>>'
      name: bar job
description: todo
foo_command:
  parameters:
    foo:
      type: string
  steps:
  - run: echo '<<parameters.foo>>'
orbs:
  aws-cli: circleci/aws-cli@0.1.6
  slack: circleci/slack@0.1.10
  utils: dialogue/sandbox@dev:utils
python:
  docker:
  - image: circleci/python:<<parameters.version>>-<<parameters.node>>
  parameters:
    node:
      default: node
      enum:
      - node
      - node-browsers
      - node-browsers-legacy
      type: enum
    version:
      default: "3.7"
      enum:
      - "3.7"
      - 3.7.2
      - 3.7.1
      - 3.7.0
      - "3.6"
      - 3.6.8
      - 3.6.7
      - 3.6.6
      - 3.6.5
      - 3.6.4
      - 3.6.3
      type: enum
version: 2.1
```

I expected:

```yml
version: 2.1
description: todo

orbs:
  aws-cli: circleci/aws-cli@0.1.6
  slack: circleci/slack@0.1.10
  utils: dialogue/sandbox@dev:utils

jobs:
  bar_job:
    parameters:
      bar:
        type: string
    steps:
      - run:
          commandn: echo '<<parameters.bar>>'
          name: bar job
      
commands:
  foo_command:
    parameters:
      foo:
        type: string
    steps:
      - run: echo '<<parameters.foo>>'
  
executors:
  python:
    docker:
    - image: circleci/python:<<parameters.version>>-<<parameters.node>>
    parameters:
      node:
        default: node
        enum:
        - node
        - node-browsers
        - node-browsers-legacy
        type: enum
      version:
        default: "3.7"
        enum:
        - "3.7"
        - "3.7.2"
        - "3.7.1"
        - "3.7.0"
        - "3.6"
        - "3.6.8"
        - "3.6.7"
        - "3.6.6"
        - "3.6.5"
        - "3.6.4"
        - "3.6.3"
        type: enum
```
