### ISSUE TITLE
Proposal: circleci orb init

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-cli#284]
I think it would be useful to have a command to scaffold a new orb. Something like `create-react-app` but for Orbs.

Here's what that may look like:

```
circleci orb init [options]

options:
--unpacked    Create an unpacked orb rather than single file (default).
--path             Path to file or directory where to create the orb. Defaults to '.'.
```

Running `circleci orb init` would create a starting point. For example, a file named `orb.yml` that looks like this:

```
version: 2.1
description: "Describe what the orb is/purpose here."

# List any Orb dependencies here
orbs:
  cli: circleci/circleci-cli@0.1.3

commands:
  my-command:
    description: "A description specifically for 'my-command'."
    parameters:
      my-param:
        description: "A description specifically for 'my-param'."
        type: string
    steps:
      - run: echo << parameters.my-param >>

jobs:
  my-job:
    description: "A description specifically for 'my-job'."
    docker:
      - image: cibuilds/base
    parameters:
      my-param:
        description: "Passes in my-param."
        type: string
    steps:
      - checkout
      - my-command:
          my-param: << parameters.my-param >>

# Below would be an actual example of how someone would use this orb.
example:
```
