### ISSUE TITLE
circleci local validate doesn't check `image:` in docker image name

### ISSUE THREAD

**Issue by ganezasan** [CircleCI-Public/circleci-cli#300]
- [*] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [*] I have checked for similar issues and haven't found anything relevant.
- [*] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Even If we don't set `image:` at the beginning of the docker image name, `circleci config validate` doesn't return an error message. 

Can you provide an example?

```
$ echo '{"jobs":{"build":{"docker":["circleci/node:latest"],"steps":[{"run":"echo\"HelloCircleCI\""}]}}}' | circleci config validate -
Config input is valid.
```

sample worng yml
```
jobs:
  build:
    docker: 
      - circleci/node:latest
    steps:
      - run: echo "Hello CircleCI"  
```
↓
sample right yml
```
jobs:
  build:
    docker: 
      - image: circleci/node:latest
    steps:
      - run: echo "Hello CircleCI"  
```

**What is the expected behavior?**
It's better to show the error message. Like this.

```
$ echo '{"jobs":{"build":{"docker":["circleci/node:latest"],"steps":[{"run":"echo\"HelloCircleCI\""}]}}}' | circleci config validate -
* Error in Config input: The schema/shape of the YAML is incorrect: json: cannot unmarshal string into Go struct field JobDescription.docker of type config.ContainerConfig *
```

**Which version of the CLI and OS are you using? Did this work in previous versions?**

```
$ circleci version
0.1.5607+f705856
```

```
$ circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/takayukiito/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, takayuki.
```
**If you have any questions, feel free to ping us at @CircleCI-Public/x-team.**
