### ISSUE TITLE
Enable Dependency Cache

### ISSUE THREAD

**Issue by Crazometer** [CircleCI-Public/circleci-cli#301]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The dependency cache doesn't work.

Attempts to use it result in

```
Error: 
Skipping cache - error checking storage: not supported

Step failed
```

Can you provide an example?

Within config .yml

```yaml

      - restore_cache:
          name: Restore Go Modules
          keys:
            - go-mod-v1-{{ checksum "./src/go.sum" }}

      - run:
          name: Install Go Modules
          command: cd src && go mod download

      - save_cache:
          name: Cache Go Modules
          key: go-mod-v1-{{ checksum "./src/go.sum" }}
          paths:
            - "/go/pkg/mod"

```

**What is the expected behavior?**

Cache should work locally! Local builds could be executed much faster.

An option to clear or skip the cache should be provided. Alternatively this could be an opt in.

The dependencies would take up space on the user's computer but a non-trivial amount of space is already used by the docker images.

**Which version of the CLI and OS are you using? Did this work in previous versions?**

OSX, latest version.
