### ISSUE TITLE
config validate should check cache keys

### ISSUE THREAD

**Issue by cansjt** [CircleCI-Public/circleci-cli#355]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

This is a feature request. Would it be possible to add a simple check that could be a nice time saver in the `config validate` command: ensure any cache key given `save_cache` command appears at least once in a `restore_cache` and vice versa. I could also be a nice cash (as in money) saver for you guys.

**What is the current behavior?**

Cache keys are not checked.

Can you provide an example?

Any `.circleci/config.yml` that contains something like
```yaml
- restore_cache:
    key: package-cache-{{ checksum "requirements.txt" }}-v1
- save_cache:
    key: packages-cache-{{ checksum "requirements.txt" }}-v1  # notice the added 's' to package
    path:
    - some/path
```
Should raise a warning or an error.

**What is the expected behavior?**

Assume the above file is being validated: 
```shell
$ circleci config vadilate
Config file at .circleci/config is not valid.
Cache "package-cache-{{ checksum "requirements.txt }}-v1" is restored but never saved.
Cache "packages-cache-{{ checksum "requirements.txt }}-v1" is saved but never restored.
$ echo $?  # Non zero value
```
**Which version of the CLI and OS are you using? Did this work in previous versions?**

```
$ circleci version
0.1.5879+416032d
```
On an Ubuntu linux machine.
```
$ circleci diagnostic
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/nicolas/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, Nicolas C.```
