### ISSUE TITLE
Bug: `matrix` valid as job-parameter

### ISSUE THREAD

**Issue by Dominik-K** [CircleCI-Public/circleci-cli#424]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant. ([Repo-wide search for `matrix` returned no results](https://github.com/CircleCI-Public/circleci-cli/search?q=matrix&unscoped_q=matrix))
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

You can set a job-parameter named `matrix` and `circleci config validate` succeeds ("Config file at .circleci/config.yml is valid.").

MWE:
```yaml
workflows:
  test-workflow:
    jobs:
      - test-orb/test-job

orbs:
  test-orb:
    jobs:
      test-job:
        parameters:
          matrix:   # <---- this shouldn't be possible
            type: string
            default: hello
        docker:
          - image: alpine
        steps:
          - run: echo hello world

version: 2.1

```
**What is the expected behavior?**

Given that `matrix` is now a reserved word in version 2.1, the validation should return with an error.

**Which version of the CLI and OS are you using? Did this work in previous versions?**

`0.1.7868+fa5217e (release)`

```
$ circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/dominik/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
```

**If you have any questions, feel free to ping us at @CircleCI-Public/x-team.**

**Comment by gmemstr** [comment]
I'm not sure if this is something we want to restrict. Given this is job level item, having a parameter named `matrix` is probably fine, and helps Orbs make semantic choices when it comes to naming parameters. Feel free to correct me however.

**Comment by Dominik-K** [comment]
@gmemstr It totally doesn't make sense to allow names for `job`-parameters which have a reserved meaning & usage when the job is used in a `workflow`. And a `job` will (nearly) always be used in a `workflow` nowadays.

Actually, the config-validation will use the reserved meaning which is the correct behavior, IMO. 

If you use the now overwritten `matrix`-parameter in the workflow, then you get an error saying `expected type: Mapping, found: String`:

```yaml
workflows:
  test-workflow:
    jobs:
      - test-orb/test-job:
          matrix: hello world	# <--- `circleci config validate` returns:  expected type: Mapping, found: String

orbs:
  test-orb:
    jobs:
      test-job:
        parameters:
          tags:   # <---- this shouldn't be possible
            type: string
            default: hello
        docker:
          - image: alpine
        steps:
          - run: echo hello world

version: 2.1

```
