### ISSUE TITLE
mkdir: command not found when using custom image locally

### ISSUE THREAD

**Issue by fizruk** [CircleCI-Public/circleci-cli#45]
I am trying out `nixorg/nix:circleci` Docker image for Circle CI, locally on macOS, using `circleci` CLI tool. However, it fails at the code checkout step with `/bin/sh: mkdir: command not found` error.

_NOTE: it works fine on Circle CI platform._

```
$ circleci build
```

```
====>> Spin up Environment
Build-agent version 0.0.5895-01cdb92 (2018-05-29T20:07:10+0000)
Starting container nixorg/nix:circleci
  using image nixorg/nix@sha256:f3fff0fca5b41722a7c41b88b0879accd6f314307eb408601c1caaa9c1b71e3d

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1533558734
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=nix
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:owner/repo.git
  CIRCLE_SHA1=dcb3199a9bf730c351918d8f2322301926bdccba
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1533558734
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/sh
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
/bin/sh: mkdir: command not found
Error: Exited with code 127
Step failed
Task failed
```

Circle CI config:

```yaml
# .circleci/config.yml
version: 2

jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - run:
          command: nix-build

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
```

Tried with these `circleci` versions:

```
$ brew install circleci
$ circleci --version
0.1.0
```

```
$ curl -o /usr/local/bin/circleci https://circle-downloads.s3.amazonaws.com/releases/build_agent_wrapper/circleci && chmod +x /usr/local/bin/circleci
$ circleci --version
0.0.5894-01cdb92
```

Documentation for `build` says:

```
circleci build --help
```

```
Run a full build locally

Usage:
  circleci build [flags]

Flags:
      ...
      --skip-checkout         use local path as-is (default true)
      ...
```

However it appears that the tool still tries to copy files over when doing

```sh
#!/bin/sh
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
```

I would appreciate any help with this, thanks!
