### ISSUE TITLE
local execute failing schema check for trigger.schedule (Config does not conform to schema)

### ISSUE THREAD

**Issue by useafterfree** [CircleCI-Public/circleci-cli#492]
## Meta:

**CircleCI CLI Version:**
`0.1.10803+6189238 (release)`

**Operating System:**
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
**CircleCI CLI Diagnostic:**

```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/*/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, Nathan *.
```
---

## Current behavior:

w/ `.circleci/config.yaml` as:
```
executors:
  seed:
    docker:
      - image: circleci/node:10-browsers
    resource_class: xlarge
jobs:
  make-seed:
    executor: seed
    steps:
      - run: |
         echo "hai"
  nightly-seed:
    when:
      equal: [master, << pipeline.git.branch >>]
    triggers:
      - schedule:
          cron: '0 22 * * *'
    jobs:
      - make-seed:
```

Yields the following behavior:

```

circleci config validate
### Error: Config does not conform to schema: {:workflows {:nightly-seed {:triggers [{:schedule {:filters missing-required-key}}]}}}

circleci local execute --job make-seed
### Error: Config does not conform to schema: {:workflows {:nightly-seed {:triggers [{:schedule {:filters missing-required-key}}]}}}

```

## Expected behavior:

`circleci local execute --job make-seed` runs without the error above

## When did this begin / Was this previously working?:
Unsure
