### ISSUE TITLE
pack of jobs results in invalid config.yml

### ISSUE THREAD

**Issue by rwc9u** [CircleCI-Public/circleci-cli#512]
## Meta:

**CircleCI CLI Version:**

```
0.1.11393+c9b8b87 (homebrew)
```

**Operating System:**

MacOS

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/robchristie/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Rob Christie.
```

## Current behavior:
Our workflows are split out:

```
 robchristie@robs-MacBook-Pro    tree config/circleci/workflows/
config/circleci/workflows/
├── @workflows.yml
├── build_and_test.yml
├── build_and_test_specs_next.yml
├── onboarding_test_cron.yml
└── onboarding_test_pr.yml
```

build_and_test.yml
```
 jobs:
  - specs
  - js_tests
  - static_analysis
  - gemfile_lock_sync_test
  - specs_feature_failures_only:
    requires:
      - specs
```

running `circleci config pack config/circleci > ./.circleci/config.yml`

The resulting config.yml has the following in the jobs

```
    build_and_test:
        jobs:
            - specs
            - js_tests
            - static_analysis
            - gemfile_lock_sync_test
            - requires:
                - specs
              specs_feature_failures_only: null
```

which is not valid

## Expected behavior:

I would have expected the pack to emit the following in that area

```
workflows:
    build_and_test:
        jobs:
            - specs
            - js_tests
            - static_analysis
            - gemfile_lock_sync_test
            - specs_feature_failures_only:
                requires:
                  - specs
```

## When did this begin / Was this previously working?:
Just noticed because we were trying to add a second job that requires another to be complete

**Comment by pete-woods** [comment]
## Triage: still reproduces on the v1 CLI

Re-ran the shape from your report against the rewritten v1 CLI:

```yaml
# workflows/build_and_test.yml
jobs:
  - specs
  - other:
    requires:
      - specs
```

```console
$ circleci config pack config/circleci
workflows:
    build_and_test:
        jobs:
            - specs
            - other: null
              requires:
                - specs
```

Same `other: null` plus a sibling `requires`, same invalid result.

Worth being precise about what is happening, because it changes what the fix should be:
the source YAML is genuinely ambiguous. `requires` is indented level with
`other:`, so it parses as a **sibling key of `other` inside the same list item**, not as
`other`'s value — `other` therefore has no value, and pack faithfully round-trips that as
`other: null`. YAML-wise pack is correct; what you meant needs `requires` indented one
level further.

Keeping this open anyway, because "faithfully reproduced your typo" is a poor experience
when the CLI can see the problem: a list item under `workflows.*.jobs` with a null-valued
job name alongside job-config keys (`requires`, `context`, `filters`, `name`, `matrix`) is
never intentional. Pack should warn — ideally with the file and line, which v1 now tracks
for parse errors — rather than emitting config that will fail at compile time.
