### ISSUE TITLE
orb pack: Print file context if "An unexpected error occurred"

### ISSUE THREAD

**Issue by Dominik-K** [CircleCI-Public/circleci-cli#519]
## Meta:

**CircleCI CLI Version:**
0.1.11393+c9b8b87 (homebrew)

**Operating System:**
macOS Catalina 10.15.7 (19H2)

---

MWE:

File `src/executors/executorA.yaml`:
```
docker:
  - image: not-relevant
    auth:
      username: $DOCKERHUB_USER
      password: $DOCKERHUB_ACCESSTOKEN
    auth:   # <- YAML error. Could be overseen when Git merge error happens.
```
and empty `src/@orb.yml`.

## Current behavior:
```
$ circleci orb pack src/ > orb.yml
Error: An unexpected error occurred: yaml: unmarshal errors:
  line 6: mapping key "auth" already defined at line 3
```

## Expected behavior:
The file where the error occurred should be printed upfront. Best in a common format like `file:line:column`. E.g. [iTerm2 recognizes this format & then you can easily click-jump there](https://stackoverflow.com/questions/38906815/can-i-click-on-a-filename-and-line-number-in-iterm2-to-open-that-file-in-visual).

## When did this begin / Was this previously working?:
Don't know.

Relates to #432.
