### ISSUE TITLE
`circleci local execute jobname` doesn't accept job parameters.

### ISSUE THREAD

**Issue by airtonix** [CircleCI-Public/circleci-cli#549]
```yaml
# .circleci/config.yml

version: 2.1

jobs:
  foo:    
    parameters:
      bar:
        type: string
   
    steps:
      - run: echo "BAR: <<parameters.bar>>" 

```

I expect to be able to do the following.

```console
$ circleci local execute foo bar:"baz"
# output is : 
# BAR: baz
```

![j0te7wq](https://user-images.githubusercontent.com/61225/106850861-2d73e700-6705-11eb-8af2-37cdd01d4ffc.jpg)
