### ISSUE TITLE
MacOSX BigSur failed to read config file: open /tmp/local_build_config.yml: permission denied when running local execute config

### ISSUE THREAD

**Issue by peucul** [CircleCI-Public/circleci-cli#575]
## Meta:

**CircleCI CLI Version:**
0.1.14827+c5ecfd4 (homebrew)

**Operating System:**
MacOSX BigSur 11.2.1

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/peuceul/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, peuceul.```

---

## Current behavior:
sudo circleci local execute -c .circleci/config.yml --job my_test 
Failed to compute task config: failed to read config file: open /tmp/local_build_config.yml: permission denied

## Expected behavior:
Trying executing a simple config, however got permission denied all the time even though /tmp folder is writeable 

## When did this begin / Was this previously working?:
This is a new installation and never worked before

## Additional Information:
other files are correctly written to /tmp

-rw-------  1 root         wheel  602 Feb 17 10:39 068193135_circleci_config.yml
-rw-------  1 root         wheel  602 Feb 17 10:22 195543844_circleci_config.yml
-rw-------  1 root         wheel  602 Feb 17 10:53 242105807_circleci_config.yml
-rw-------  1 root         wheel  602 Feb 17 10:52 301869490_circleci_config.yml
-rw-------  1 root         wheel  602 Feb 17 10:38 422458357_circleci_config.yml
-rw-------  1 root         wheel  602 Feb 17 10:35 726251506_circleci_config.yml
-rw-------  1 root         wheel  602 Feb 17 10:38 900763571_circleci_config.yml
```

I changed also permission of /tmp with chmod 777 and still having the same error.
I also added /tmp/local_build_config.yml manually (using vim) and chmod 777 the file, but it did not help.

Config.yml is as following, where I managed to spawn and interact with debian container manually 
```
version: 2.1
jobs:
  my_test:
    machine:
      image: debian:stretch
    steps:
      - run:
          name: "Create folder"
          command: mkdir -p /opt/
workflows:
  browser:
    jobs:
      - my_test
```

**Comment by vizarch** [comment]
Local execution works only with docker, not machine:

try:
```
docker:
      - image: docker:stable-git
..
..
 and add setup_remote_docker step
```

**Comment by peucul** [comment]
@vizarch 

```
version: 2.1
jobs:
  my_test:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: "Create folder"
          command: mkdir -p /opt/
      - setup_remote_docker:
          version: 18.06.0-ce
workflows:
  browser:
    jobs:
      - my_test
```

still returned me with 
failed to read config file: open /tmp/local_build_config.yml: permission denied
