### ISSUE TITLE
When condition disappears after `circleci config process` command

### ISSUE THREAD

**Issue by chapmanc** [CircleCI-Public/circleci-cli#624]
## Meta:

**CircleCI CLI Version:**

0.1.15900+a651f78

**Operating System:**
mac

## Current behavior:
Using the examples https://circleci.com/docs/2.0/configuration-reference/#logic-statements
I have tried to include it on our existing config.yml which processes several orbs (all 2.1) and then packages them. The circleci tool validates correctly and there are no errors in the process command but it strips out the when conditions for the workflows 

Commands run: 
`circleci config pack .circleci/config >> testconf.yml && circleci config process testconf.yml`

This inside our .circleci/config/@config.yml:
```
version: 2.1
....
workflows:
  trigger_job:
    when:
      and:
        - equal [ << pipeline.parameters.trigger_job >> ]
    jobs:
      - e2e_job
```
becomes this without the when logic:
```
version: 2
workflows:
  trigger_job:
    jobs:
    - e2e_job
  version: 2
```

## Expected behavior:
The conditional logic should persist or the circleci version should stay at 2.1? 

## When did this begin / Was this previously working?:
Trying to leverage the logic statements that are available so not sure if this ever worked.

## Additional Information:
No
