### ISSUE TITLE
circleci config validate doesn't work with scheduled pipeline variables

### ISSUE THREAD

**Issue by nbialostosky** [CircleCI-Public/circleci-cli#640]
## Meta:

**CircleCI CLI Version:**
0.1.16192+b65f946 (homebrew)

**Operating System:**
MacOS Big Sur

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/<username>/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
```

---

## Current behavior:
At the moment when you include `<< pipeline.trigger_source >>`, `<< pipeline.schedule.name >>` , `<< pipeline.schedule.id >>` in your config file, then run `circleci config validate` it notes these are not valid values. This isn't the case, they are and work when the config is actually used in a build.

```
Error: Error calling workflow: 'build-logic'
Error calling job: 'build'
Unknown variable(s): id, trigger_source, name
```

## Steps to replicate
1. Use this as your `config.yml` in your `.circleci` directory:

```
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: echo << pipeline.trigger_source >>
      - run: echo << pipeline.schedule.name >>
      - run: echo << pipeline.schedule.id >>

workflows:
  build-logic:
    jobs:
      - build
```

2. run `circleci config validate` 

## Expected behavior:
The `circleci config validate` command should note the config is valid, as it is.

## When did this begin / Was this previously working?:
This began when these variables were introduced with scheduled pipelines.
