### ISSUE TITLE
local execution checkout failing for Git LFS

### ISSUE THREAD

**Issue by rynkowsg** [CircleCI-Public/circleci-cli#644]
## Meta:

**CircleCI CLI Version:**
```
% circleci version
0.1.16225+8d5e389 (homebrew)
```

**Operating System:**
macOS Catalina 10.15.7

**CircleCI CLI Diagnostic:**

```
% circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/greg/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Grzegorz Rynkowski.
```

---

## Current behavior:
```
% circleci local execute --job print_ver -e CIRCLE_PROJECT_USERNAME=secret-org -e CIRCLE_PROJECT_REPONAME=some-project
Docker image digest: sha256:2c2fd6a4655b259ac40f3c168b82200d4a7cebdc8287c4eb866a348b0191403d
====>> Spin Up Environment
Build-agent version  ()
Docker Engine Version: 20.10.6
Kernel Version: Linux 8d1d94408128 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 Linux
Starting container cimg/base:2021.10-20.04
  image is cached as cimg/base:2021.10-20.04, but refreshing...
2021.10-20.04: Pulling from cimg/base
Digest: sha256:d7f9934c0cfb3cbb1d58007c1eaceff082b8dd0965993db33c555b58e5bf8d73
Status: Image is up to date for cimg/base:2021.10-20.04
  using image cimg/base@sha256:d7f9934c0cfb3cbb1d58007c1eaceff082b8dd0965993db33c555b58e5bf8d73
====>> Preparing Environment Variables
Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1636559968
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=some-branch-name
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=print_ver
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:secret-org/some-project.git
  CIRCLE_SHA1=cbd28970570bdb66c7c6bcd578cabbd267cd018a
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1636559968
  CIRCLE_WORKING_DIRECTORY=~/code

Using environment variables from project settings and/or contexts:
  CHECKOUT_KEY=**REDACTED**
  CIRCLE_PROJECT_REPONAME=**REDACTED**
  CIRCLE_PROJECT_USERNAME=**REDACTED**
  CIRCLE_USERNAME=**REDACTED**

The redacted variables listed above will be masked in run step output.====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /home/circleci/code && cd /tmp/_circleci_local_build_repo && git ls-files | tar -T - -c | tar -x -C /home/circleci/code && cp -a /tmp/_circleci_local_build_repo/.git /home/circleci/code
tar: "docs/Example1.pdf": Cannot stat: No such file or directory
tar: "docs/Example2.pdf": Cannot stat: No such file or directory
tar: "docs/Example3.pdf": Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Error:
Exited with code exit status 2

Step failed
Error: runner failed (exited with 101)
Task failed
Error: task failed
```

## Expected behavior:
The job should not crash at the checkout step.

## Additional Information:
Job:
```
jobs: 
  print_ver:
    docker: [ { image: cimg/base:2021.10-20.04 } ] # https://hub.docker.com/r/cimg/base/tags
    working_directory: ~/code
    resource_class: small
    description: "Debug task only for testing purposes"
    steps:
      - checkout
      - run: { name: "Print Hello", command:  echo "Hello" }
```
