### ISSUE TITLE
Pipeline parameter value type inconsistent between cloud and local execute

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/circleci-cli#673]
## Meta:

**CircleCI CLI Version:**
0.1.16535+5010eb7 (release)

**Operating System:**
macOS Monterey v12.2
Apple M1 Pro

---

## Current behavior:

A simplified version of my config looks like this:

```yaml
workflows:
  lint-pack:
    jobs:
      - orb-tools-alpha/lint
      - orb-tools-alpha/pack
      - orb-tools-alpha/review
      - orb-tools-alpha/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools-alpha/publish-dev]
```

In the `orb-tools-alpha/continue` job, there is a parameter `pipeline-number`, which expects an integer value which will be injected when running on CircleCI. I do not actually need to run this job locally, however because of a config error that occurs locally I am unable to locally execute other jobs.

```shell
$ circleci local execute --job orb-tools-alpha/lint
Error: Error calling workflow: 'lint-pack'
Error calling job: 'orb-tools-alpha/continue'
Type error for argument pipeline-number: expected type: integer, actual value: "1" (type string)
```

On CircleCI Cloud the correct value `i` is injected. It seems when locally invoked, a _string_ `"1"` is injected. This leads to a config failure that prevents local execution of any jobs in the config.

## Expected behavior:

Inject mock values for pipeline parameters locally and ensure they are of the same type as CircleCI cloud. Local execution should expect the same types as cloud.
