### ISSUE TITLE
Local CircleCI doesn't support 2.1 preview

### ISSUE THREAD

**Issue by brianmhunt** [CircleCI-Public/circleci-cli#79]
I just downloaded circleci from the usual:

> curl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh --fail --show-error | bash

It reports version:

```
$ circleci version
0.1.1568+255077c
```

Possible aside: I noted that `circleci switch` does nothing.

When I run something locally with the config-preview-sdk (i.e. `version: 2.1`) it errors with config parsing issues that indicate that it's not using the preview SDK e.g.

```
version: 2.1
...
jobs:
  deploy:
     executor:
        name: some-custom-executor
...      
```

```
* Error in config file: The schema/shape of the YAML is incorrect: json: cannot unmarshal object into Go struct field JobDescription.Executor of type string
```

I seem to be missing something, and guidance would be appreciated.
