### ISSUE TITLE
Failing to read config file while executing process.yml

### ISSUE THREAD

**Issue by filip-aipl** [CircleCI-Public/circleci-cli#801]
## Meta:

**CircleCI CLI Version:**
  0.1.22322+5ff92b4 (homebrew)

**Operating System:**
macOS Monterey 12.2.1 

**CircleCI CLI Diagnostic:**

```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/filip/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Filip Nowak.
```

---

## Current behavior:

```
# .circleci/config.yml
orbs:
  docker: circleci/docker@2.1
  orb-tools: circleci/orb-tools@10.1.0
  # some private orbs there, they are valid
version: 2.1
jobs:
  test:
    docker:
      - image: test_img # (local docker image)
    steps:
      - command_from_private_orb
workflows:
  test_wf:
    jobs:
    - test
```

```
# process.yml or .circleci/process.yml - tested both ways
# Orb 'circleci/docker@2.1' resolved to 'circleci/docker@2.1.4'
# Orb 'circleci/orb-tools@10.1.0' resolved to 'circleci/orb-tools@10.1.0'
# private orbs resolved correctly
version: 2
jobs:
  test:
    docker:
    - image: test_img
    steps:
    - run:
        command: valid_command_from_private_orb
        name: valid name of the command 
workflows:
  test_wf:
    jobs:
    - test
  version: 2
```

I am trying to run job named `test` from this config locally. Doing this by executing two commands:
```circleci config process .circleci/config.yml -o github/my_valid_org > process.yml```
and then 
```sudo circleci local execute -c process.yml --job test``` (and also without sudo)

I tried this few times with different configurations, external dockerfile and getting the same result.
```
Fetching latest build environment...
Docker image digest: some_docker_sha
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Error: failed to start event processor: failed to compute task config: failed to read config file: open /tmp/local_build_config.yml: operation not permitted
```
I am getting this error in every attempt.  I even built the docker image locally. 
## Expected behavior:

I do not know what should happen next, but finally I would like to see output from the command in `test` job.
## When did this begin / Was this previously working?:

I am working on this few days and haven't managed to make it work correctly. Also, I haven't worked before with running CircleCI jobs locally.

## Additional Information:

Worth to mention: the command from the orb is working correctly in the CircleCI app. I searched similar issue and found that this should be resolved in one of the releases (https://github.com/CircleCI-Public/circleci-cli/issues/391 and maybe https://github.com/CircleCI-Public/circleci-cli/issues/212) but the error appears again.
The authorization process is working, I am getting valid responses from private orbs. I upgraded the CircleCI version to newest possible. Docker in the system is running properly, executing the command from private orb alone also works.
