### ISSUE TITLE
Invalid config file shows as valid

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-cli#83]
I have the following config file:

```
version: 2
jobs:
   build:
    docker:
      - image: cibuilds/hugo:0.46
    docker:jj:
    steps:
      - checkout
      - run:
          name: "Build Website With  Hugo"
          command: echo "Hi"
```

There's at least two errors here. Line 3 has 3 spaces and line 4 is an invalid key as well as doesn't have a value. This file validates.

CLI version: 0.1.1640+4a9a3c9
Installed method: cURL
Build-agent version: The CLI doesn't say

Technically this is valid YAML, but not a CircleCI config. I guess we haven't gotten that far yet?
