### ISSUE TITLE
`circleci config validate` misses invalid job name in workflow if workflow is skipped by default

### ISSUE THREAD

**Issue by danxmoran** [CircleCI-Public/circleci-cli#844]
## Meta:

**CircleCI CLI Version:**

`0.1.23391+5cbf90e (homebrew)` (Mac) and `0.1.23241` (Linux)

**Operating System:**

MacOS and Linux

---

## Current behavior:

If you have config like this:
```yaml
version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base
    steps:
      - run: echo hello
  job2:
    docker:
      - image: cimg/base
    steps:
      - run: echo world
 
parameters:
  run_invalid:
    type: boolean
    default: false

workflows:
  invalid:
    when: << pipeline.parameters.run_invalid >>
    jobs:
      - job1:
          name: job_renamed
      - job2:
          requires:
            - job1 # Error is here, should be `job_renamed`
```

`circleci config validate` says the config is valid, even though it's not.

## Expected behavior:

`circleci config validate` should flag the invalid job name in the `requires`.

## When did this begin / Was this previously working?:

Unsure

## Additional Information:

The config is properly flagged as invalid if I flip the default value of `run_invalid` from `false` to `true`
